### ISSUE TITLE
[Bug]: wrong confidence intervals in random effects meta-analysis with option knha

### ISSUE THREAD

**Issue by angonzamp** [jasp-stats/jasp-issues#1740]
### JASP Version

0.16.2

### JASP Module

jaspMetaAnalysis

### What analysis are you seeing the problem on?

Confidence interval of the Estimate in Random Effects meta-analysis with the knha option

### What OS are you seeing the problem on?

Windows 10 Home Edition 

### Bug Description

The CI in the estimate is clearly wrong in the table and different from the included in the forest plot. I tested two RE methods: Restricted ML and Sidik-Jonkman obtaining the same result. In contrast the CI obtained with the z option were correct.
I attach a file with the wrong CI.
![CI discordant](https://user-images.githubusercontent.com/107149319/172709470-6c6651c0-fa5e-4af7-9b41-d955496f4cbb.jpg)

### Expected Behaviour

The CI should be as in the Forest plot.

### Steps to Reproduce

1. The problem has happened with all meta-analysis I tried.
2. 
3. 
...

### Log (if any)

[JASP 2022-06-08 22_02_30 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/8864856/JASP.2022-06-08.22_02_30.Desktop.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
@sophieberkhout Can you have a look at this issue?

**Comment by tomtomme** [comment]
@angonzamp 
Tested with 0.18.3 and the data library data set. Seems fixed.
Feel free to reopen if not fixed on your side.
