### ISSUE TITLE
"Copy Citations" for Bayesian Meta-Analysis

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#875]
Meta-analysis module -> Bayesian meta-analysis.

Currently, the "copy citations" feature offers no useful references. Actually, the help file *is* really good in that respect. Can we:
1. Make available the references from the help file in the "copy citations" feature? (as an aside, should this be done automatically, for all analyses?)
2. Add, both to the help file *and* to the "copy citations" feature, the following key reference:

Gronau, Q. F., Heck, D. W., Berkhout, S. W., Haaf, J. M., & Wagenmakers, E.-J. (2020). A primer on Bayesian model-averaged meta-analysis. https://psyarxiv.com/97qup.

**Comment by JorisGoosen** [comment]
Yeah this is what the plan is with the combination of https://github.com/jasp-stats/INTERNAL-jasp/issues/445 and https://github.com/jasp-stats/INTERNAL-jasp/issues/740

**Comment by tomtomme** [comment]
@JorisGoosen & @boutinb 
I gather all missing "citation" features from different issues here as an overview:

- [ ] That reference is still missing in Bayesian Meta-Analysis (Gronau, Q. F., Heck, D. W., Berkhout, S. W., Haaf, J. M., & Wagenmakers, E.-J. (2020). A primer on Bayesian model-averaged meta-analysis. https://psyarxiv.com/97qup.)
- [ ] "copy citations" button should copy references from the help file
- [ ] showing citations as a popup, when hovering the "copy citations" button (from https://github.com/jasp-stats/jasp-issues/issues/166)
- [ ] display which R package is responsible for which output, e.g. pca (psych), sem (lavaan), network (bootnet) and add them in addition to the references when clicking "copy citations" **(from https://github.com/jasp-stats/jasp-issues/issues/140)
- [ ] Show all the above automatically when R-Syntax output is turned on
